wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    mask/class_labels:
      Images [training]_wandb_delimeter_ground_truth:
        key: Images [training]_wandb_delimeter_ground_truth
        type: mask/class_labels
        value:
          '0': background
          '1': fire
          '2': smoke
      Images [training]_wandb_delimeter_prediction:
        key: Images [training]_wandb_delimeter_prediction
        type: mask/class_labels
        value:
          '0': background
          '1': fire
          '2': smoke
    python_version: 3.10.2
    start_time: 1667568439.727352
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 63
      - 74
      - 80
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 63
      - 74
      - 80
      3:
      - 2
      - 23
      4: 3.10.2
      5: 0.13.5
      8:
      - 3
      - 5
adam_epsilon:
  desc: null
  value: 0.01
amp:
  desc: null
  value: true
batch_size:
  desc: null
  value: 56
epochs:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.01
patch_size:
  desc: null
  value: 256
save_checkpoint:
  desc: null
  value: true
weight_decay:
  desc: null
  value: 0.001
